# arena_layout.py
"""Geometry of the 2.4 m x 2.4 m obstacle arena, as pure numpy / trimesh.

This is the practice course from the design drawing: an OSB deck with two 10 cm
beams crossing it corner to corner (the fabrication guide's diagonal K-rails), a
milk crate where they meet, a wooden fence along the north and south edges, and
a half-length fence along the north half of the east edge and the south half of
the west edge. Each half fence carries the drawing's "linear rail" at 60 cm,
which is the guide's Linear Align/Inspect task (printed pp. 69-72): a green rail
with five capped pipes, each hiding a 5 cm acuity target. The whole thing has
180-degree rotational symmetry about the deck centre, so only the north fence
and the east task are described here and the other half is generated by
rotating them.

Frame. The arena centre is the origin, x east, y north, z up, floor at z = 0.
The deck top is at `DECK_THICKNESS`; every height quoted for the frame is above
the DECK, matching the drawing's annotations. The drawing's plan view is read
with north up, so the two START|END boxes are "sw" (bottom-left) and "ne"
(top-right). Both marked paths enter and leave the deck through the two open
half-edges (south half of the east edge, north half of the west edge) and cross
two beams on the way.

Everything here is static terrain. `competition/geometry.py` builds the same
square from the guide's components with textured targets for the competition
launcher; this is the lighter version behind the default sim world.

Nothing here imports Isaac Lab, so the module can be tested and plotted outside
the simulator. `arena_terrain.py` wraps it for the terrain generator.
"""
from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np
import trimesh

# ---------------------------------------------------------------------------
# Dimensions, metres. The three the drawing annotates are exact; the rest are
# read off the plan at ~120 px/m and rounded to standard lumber sizes.
# ---------------------------------------------------------------------------
DECK_SIZE = 2.4                 # "Overall Size: 2.4 m x 2.4 m"
DECK_HALF = DECK_SIZE / 2
DECK_THICKNESS = 0.018          # one OSB sheet laid on the floor; the drawing gives no deck height
BEAM_WIDTH = 0.06
BEAM_HEIGHT = 0.10              # "Obstacle Height: 10 cm"
CRATE_SIZE = (0.33, 0.33, 0.28)  # the blue perforated box at the centre is a milk crate
POST = 0.09                     # 4x4 posts
POST_HEIGHT = 0.69              # above the deck; the cap lies flat across the post tops
CAP_RAIL_Z = (0.65, 0.69)       # 2x4 flat on the posts, just above the inspect task
CAP_RAIL_WIDTH = POST
MID_RAIL_Z = (0.275, 0.365)     # 2x4 on edge, ~45 % of the post height in the drawing
RAIL_WIDTH = 0.04
FLOOR_THICKNESS = 0.10

# Linear Align/Inspect task, guide pp. 69-72. A 90 cm 2x2 rail lies flat against the
# wall with a 30 cm 2x4 centre piece cut to a trapezoid on its face; both lie on their
# sides, so the fixture is 5 cm tall. Five capped 5 cm PVC pipes point into the arena:
# two straight out at +-30 cm, one on each 45-degree face, one on the top face. A 5 cm
# acuity target sits at the bottom of each pipe; here it is a disc in the target's ring
# colour, so a camera looking down the pipe still has a colour to identify.
TASK_ELEVATION = 0.60           # "Linear Rail Height: 60 cm": the rail's underside
TASK_LUMBER = 0.05
PIPE_OUTER, PIPE_INNER, PIPE_LENGTH = 0.030, 0.025, 0.05
CAP_RADIUS, CAP_THICKNESS = 0.034, 0.006
TARGET_RADIUS = 0.024
# Acuity sets 1 (east task) and 2 (west task) from p. 72, in the viewer's order when
# facing the wall: left 90 deg, left 45 deg, centre, right 45 deg, right 90 deg.
TARGET_COLOURS = {
    "east": ([245, 140, 25], [217, 25, 25], [250, 204, 13], [25, 140, 64], [25, 77, 191]),
    "west": ([217, 25, 25], [25, 140, 64], [245, 140, 25], [25, 77, 191], [250, 204, 13]),
}

# The robot's spawn poses: (x, y, z), yaw in radians. Positions are the centres
# of the two START|END boxes in the drawing. z is the standing height the rest
# of the sim uses. Each faces the direction its path leaves in.
START_POSES = {
    # bottom-left box. The "Down Range path" starts here and heads north up the
    # outside of the west edge.
    "sw": ((-1.8, -1.2, 0.42), math.radians(90.0)),
    # top-right box. The "Up Range path" starts here and heads south down the
    # outside of the east edge.
    "ne": ((1.8, 0.9, 0.42), math.radians(-90.0)),
}
DEFAULT_START = "sw"

# Colours, RGBA 0-255, matching the drawing.
C_FLOOR = [150, 150, 150, 255]
C_DECK_N = [214, 178, 110, 255]
C_DECK_S = [204, 168, 102, 255]   # the seam between the two sheets shows as a tint change
C_BEAM = [243, 150, 52, 255]
C_CRATE = [30, 80, 220, 255]
C_POST = [120, 70, 30, 255]
C_RAIL = [150, 92, 42, 255]
C_TASK = [20, 140, 40, 255]       # "Align/Inspect Tasks (Green)"
C_PVC = [235, 235, 230, 255]


@dataclass(frozen=True)
class Box:
    center: tuple[float, float, float]
    size: tuple[float, float, float]
    color: list[int]
    yaw: float = 0.0  # radians about z

    def rotated_180(self) -> "Box":
        cx, cy, cz = self.center
        return Box((-cx, -cy, cz), self.size, self.color, self.yaw)


def _half_structure(deck_thickness: float) -> list[Box]:
    """The north fence and the east half fence; the other half is this rotated 180 degrees."""
    z0 = deck_thickness
    d = DECK_HALF + POST / 2            # post centre line, just outside the deck edge
    post_top = z0 + POST_HEIGHT
    boxes = []

    def post(x, y):
        boxes.append(Box((x, y, post_top / 2), (POST, POST, post_top), C_POST))

    def rail_x(y, z_lo, z_hi, x0, x1, width):
        boxes.append(Box(((x0 + x1) / 2, y, z0 + (z_lo + z_hi) / 2),
                         (x1 - x0, width, z_hi - z_lo), C_RAIL))

    def rail_y(x, z_lo, z_hi, y0, y1, width):
        boxes.append(Box((x, (y0 + y1) / 2, z0 + (z_lo + z_hi) / 2),
                         (width, y1 - y0, z_hi - z_lo), C_RAIL))

    # North fence: three posts on the line y = d, a flat cap and a middle rail between
    # the corner posts' inner faces (the middle post is just overlapped).
    for x in (-d, 0.0, d):
        post(x, d)
    rail_x(d, *CAP_RAIL_Z, -DECK_HALF, DECK_HALF, CAP_RAIL_WIDTH)
    rail_x(d, *MID_RAIL_Z, -DECK_HALF, DECK_HALF, RAIL_WIDTH)

    # East half fence, north half of the east edge. Its north post is the fence's
    # corner post; its south post ends at the deck's centre line.
    post(d, POST / 2)
    y0, y1 = POST, DECK_HALF            # between the two posts' inner faces
    rail_y(d, *CAP_RAIL_Z, y0, y1, CAP_RAIL_WIDTH)
    rail_y(d, *MID_RAIL_Z, y0, y1, RAIL_WIDTH)
    return boxes


def arena_boxes(deck_thickness: float = DECK_THICKNESS,
                obstacle_height: float = BEAM_HEIGHT) -> list[Box]:
    """Every box-shaped part of the arena, about the arena centre, floor at z = 0. No floor slab."""
    z0 = deck_thickness
    boxes = [
        # Two 2.4 x 1.2 sheets, seam along the x axis.
        Box((0.0, DECK_HALF / 2, z0 / 2), (DECK_SIZE, DECK_HALF, z0), C_DECK_N),
        Box((0.0, -DECK_HALF / 2, z0 / 2), (DECK_SIZE, DECK_HALF, z0), C_DECK_S),
        # The crate at the crossing.
        Box((0.0, 0.0, z0 + CRATE_SIZE[2] / 2), CRATE_SIZE, C_CRATE),
    ]
    # Corner-to-corner beams. Shortened by one beam width so the rectangle's
    # corners land exactly on the deck edges instead of poking past them.
    beam_len = DECK_SIZE * math.sqrt(2.0) - BEAM_WIDTH
    for yaw in (math.radians(45.0), math.radians(-45.0)):
        boxes.append(Box((0.0, 0.0, z0 + obstacle_height / 2),
                         (beam_len, BEAM_WIDTH, obstacle_height), C_BEAM, yaw))
    half = _half_structure(z0)
    boxes.extend(half)
    boxes.extend(b.rotated_180() for b in half)
    return boxes


def box_mesh(box: Box) -> trimesh.Trimesh:
    b = trimesh.creation.box(extents=box.size)
    if box.yaw:
        b.apply_transform(trimesh.transformations.rotation_matrix(box.yaw, [0.0, 0.0, 1.0]))
    b.apply_translation(box.center)
    b.visual.vertex_colors = box.color
    return b


# ---------------------------------------------------------------------------
# The inspect tasks: not boxes, so built as meshes directly
# ---------------------------------------------------------------------------
def _coloured(mesh: trimesh.Trimesh, color) -> trimesh.Trimesh:
    mesh.visual.vertex_colors = list(color[:3]) + [255]
    return mesh


def _prism(polygon, z0: float, z1: float, color) -> trimesh.Trimesh:
    """Closed extrusion of a counter-clockwise convex polygon between two heights."""
    xy = np.asarray(polygon, dtype=float)
    n = len(xy)
    vertices = np.vstack((np.column_stack((xy, np.full(n, z0))),
                          np.column_stack((xy, np.full(n, z1)))))
    faces = []
    for i in range(1, n - 1):
        faces += [(0, i + 1, i), (n, n + i, n + i + 1)]
    for i in range(n):
        j = (i + 1) % n
        faces += [(i, j, n + j), (i, n + j, n + i)]
    return _coloured(trimesh.Trimesh(vertices, np.array(faces), process=False), color)


def _along_axis(mesh: trimesh.Trimesh, foot, axis, length: float) -> trimesh.Trimesh:
    """Place a trimesh primitive (built centred on the origin along z) so that it starts at
    `foot` and runs `length` along the horizontal unit `axis`."""
    ax, ay = axis
    right, up, forward = (-ay, ax, 0.0), (0.0, 0.0, 1.0), (ax, ay, 0.0)
    transform = np.eye(4)
    transform[:3, :3] = np.column_stack((right, up, forward))
    transform[:3, 3] = np.asarray(foot, dtype=float) + np.array(forward) * length / 2
    mesh.apply_transform(transform)
    return mesh


def linear_inspect_task(mount, facing, colours, deck_thickness: float = DECK_THICKNESS,
                        elevation: float = TASK_ELEVATION) -> list[trimesh.Trimesh]:
    """One task, in arena coordinates. `mount` is the centre of the wall's inner face in the
    plan, `facing` the unit direction into the arena, `colours` the five target colours in
    the viewer's order when facing the wall."""
    fx, fy = facing
    forward = np.array([fx, fy, 0.0])
    along = np.array([fy, -fx, 0.0])          # right-handed with forward and up
    up = np.array([0.0, 0.0, 1.0])
    base = np.array([mount[0], mount[1], deck_thickness])
    z0, z1 = elevation, elevation + TASK_LUMBER
    z_mid = (z0 + z1) / 2
    parts = []

    def place(mesh):
        v = mesh.vertices
        mesh.vertices = base + v[:, :1] * along + v[:, 1:2] * forward + v[:, 2:3] * up
        parts.append(mesh)

    rail = trimesh.creation.box(extents=(0.9, TASK_LUMBER, TASK_LUMBER))
    rail.apply_translation((0.0, TASK_LUMBER / 2, z_mid))
    place(_coloured(rail, C_TASK))
    place(_prism([(-0.15, 0.05), (0.15, 0.05), (0.05, 0.15), (-0.05, 0.15)], z0, z1, C_TASK))
    s = math.sqrt(0.5)
    # Viewer's left to right when facing the wall, which is -along: (x along the wall,
    # y out from the wall face, pipe axis).
    pipes = ((0.30, 0.05, (0.0, 1.0)), (0.10, 0.10, (s, s)), (0.0, 0.15, (0.0, 1.0)),
             (-0.10, 0.10, (-s, s)), (-0.30, 0.05, (0.0, 1.0)))
    for (x, y, axis), colour in zip(pipes, colours):
        foot = np.array([x, y, z_mid])
        cap_end = foot + CAP_THICKNESS * np.array([*axis, 0.0])
        place(_along_axis(_coloured(trimesh.creation.cylinder(CAP_RADIUS, CAP_THICKNESS, sections=16), C_PVC),
                          foot, axis, CAP_THICKNESS))
        place(_along_axis(_coloured(trimesh.creation.annulus(PIPE_INNER, PIPE_OUTER, PIPE_LENGTH, sections=16), C_PVC),
                          cap_end, axis, PIPE_LENGTH))
        place(_along_axis(_coloured(trimesh.creation.cylinder(TARGET_RADIUS, 0.002, sections=16), colour),
                          cap_end, axis, 0.002))
    return parts


def arena_fixtures(deck_thickness: float = DECK_THICKNESS,
                   rail_height: float = TASK_ELEVATION) -> list[trimesh.Trimesh]:
    """Both inspect tasks: on the east half fence facing west, and its 180-degree copy."""
    y_mid = (POST + DECK_HALF) / 2                    # middle of the half fence's inner span
    east = linear_inspect_task((DECK_HALF, y_mid), (-1.0, 0.0), TARGET_COLOURS["east"],
                               deck_thickness, rail_height)
    west = linear_inspect_task((-DECK_HALF, -y_mid), (1.0, 0.0), TARGET_COLOURS["west"],
                               deck_thickness, rail_height)
    return east + west


def yaw_quat_wxyz(yaw: float) -> tuple[float, float, float, float]:
    return (math.cos(yaw / 2), 0.0, 0.0, math.sin(yaw / 2))


def start_pose(name: str = DEFAULT_START):
    """(pos xyz, rot wxyz) for a START|END box, as an ArticulationCfg init_state wants it."""
    pos, yaw = START_POSES[name]
    return tuple(pos), yaw_quat_wxyz(yaw)


def build_arena_meshes(floor_size: tuple[float, float],
                       center: tuple[float, float] = (0.0, 0.0),
                       deck_thickness: float = DECK_THICKNESS,
                       obstacle_height: float = BEAM_HEIGHT,
                       rail_height: float = TASK_ELEVATION) -> list[trimesh.Trimesh]:
    """The arena plus a `floor_size` slab under it (top at z = 0), translated so the
    arena centre sits at `center`."""
    floor = Box((0.0, 0.0, -FLOOR_THICKNESS / 2),
                (floor_size[0], floor_size[1], FLOOR_THICKNESS), C_FLOOR)
    meshes = [box_mesh(b) for b in [floor] + arena_boxes(deck_thickness, obstacle_height)]
    meshes += arena_fixtures(deck_thickness, rail_height)
    for m in meshes:
        m.apply_translation([center[0], center[1], 0.0])
    return meshes


def describe(deck_thickness: float = DECK_THICKNESS,
             obstacle_height: float = BEAM_HEIGHT,
             rail_height: float = TASK_ELEVATION) -> str:
    return (f"[ARENA] {DECK_SIZE:.1f} m x {DECK_SIZE:.1f} m deck ({deck_thickness * 1000:.0f} mm), "
            f"{obstacle_height * 100:.0f} cm diagonal beams, crate at centre, "
            f"two linear inspect tasks at {rail_height * 100:.0f} cm with 5 pipes each; "
            f"start boxes: " + ", ".join(f"{k}=({p[0]:+.1f}, {p[1]:+.1f}) yaw {math.degrees(y):+.0f} deg"
                                         for k, (p, y) in START_POSES.items()))
